language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
before_script:
  - npm prune
script:
  - yarn test:coverage
after_success:
  - yarn report-coverage
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
